name: crates.io publishing

on:
  pull_request: # FIXME: Remove
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

jobs:
  custom-release-checks:
    uses: ./.github/workflows/release-checks.yml
    secrets: inherit

  deploy:
    needs:
      - custom-release-checks
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}
    permissions:
      contents: write
      id-token: write # Required for Trusted Publishing OIDC
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Common setup
        uses: ./.github/actions/common
        with:
          toolchain: stable

      - name: Publish on crates.io
        run: |
          #cargo publish --provenance
